### ISSUE TITLE
Open either *.xcodeproj or *.xcworkspace from a single directory

### ISSUE THREAD

**Issue by RobertAudi** [erica/xcopen#2]
First of all, thanks for this awesome utility. I had built something similar as a Zsh function, but it had its quirks.

One thing that is a bit annoying in your version is that the default behavior opens _too much_.

When a project has both one or many `*.xcodeproj` files alongside a `*.xcworkspace`, everything is being opened. The preferred behavior in my opinion would be to open the workspace if it there and ignore the project files.

After reading the source code I suspected that you came to a similar realization since you added undocumented subcommands (`ws` in particular).

One potential solution – apart or in addition to from changing the default behavior – would be to adopt the current default behavior only when the `--all` flag is passed.

**Comment by erica** [comment]
That sounds reasonable. Do a search for xcworkspace: if it exists, just open that.

Let me see what I can do.

**Comment by erica** [comment]
@RobertAudi 

Please update and test. Thank you!

**Comment by RobertAudi** [comment]
@erica Seems to work without any arguments. However if you try to open a project explicitly (instead of the workspace), then the "Welcome to Xcode" window opens instead, which leads me to believe that the argument is being ignored – in other words, the command that is being executed is something similar to this:

```console
$ open -a Xcode
```

I also tried to run `xcopen` without any arguments in a directory with only playgrounds and nothing happened (which leads me to believe that nothing was found), and with the playground as argument the same as above happens.

I don't know if that's a regression but I'm pretty sure it's a bug 😕

**Comment by RobertAudi** [comment]
Here is the offending code:

https://github.com/erica/xcopen/blob/7e0eeeb78f9b85b6c2b2f35dc775bfcd45ffb092/xcopen/main.swift#L31-L41

If there is no arguments then you only check for either a workspace or a project.

What do you think about this behavior instead:

- If no arguments are passed
  - If there is a workspace, open it
  - Otherwise, fallback to the previous default behaviour
- It there are arguments
  - Use the same behavior as before

**Comment by erica** [comment]
It's a mix of intentional behavior and bug (playgrounds), as I was intending to open flat files and not directories as named arguments.

I think I have an approach to work with this though. Instead of ignoring directories, I'll use the other open style. I'll push another take shortly for you to try.

**Comment by erica** [comment]
No arguments:

xcworkspace exists: open it. done.
otherwise, open any xcodeproj or playground.
No other xc extensions recognized

Arguments:

open any xcodeproj, xcworkspace, playground with `open`.

open any flat file with `open -a xcode`

This leaves directories/folders that cannot be normally opened with Xcode, meaning that they should either be ignored or the files inside them should be opened, and a policy has to be picked for that. What do you suggest?

Final special cases: "." and "..": how should they act?

**Comment by erica** [comment]
@RobertAudi Please test new version and let me know if you disagree with the policies for arguments.

**Comment by RobertAudi** [comment]
@erica The latest version works like a charm 👍🏻

As for the case of directories, I agree with you, they shouldn't be dealt with. If you try to open a directory manually with Xcode (e.g.: `open -a Xcode ./tmp/`) you get an error in an alert window (standard behavior). On top of my head there are two ways to approach the problem:

1. Run the `open` command and let Xcode show the error
2. Ignore the command and show an error/warning message on the command line

IMHO the second case is really a "nice to have" feature and it's completely fine to just ignore the command (this is the current behavior), but as far as I'm concerned the tool works really well at this point.

As an "extra nice to have" feature, you could try to apply the default behavior in the directory passed as argument but I think this is definitely out of the scope of this issue.

Anyway thanks a lot for your responsiveness and good job! 👏🏻

I'm going to replace my home-made shell function with this tool now 😁

**Comment by erica** [comment]
Thanks for the feedback.
